// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vWi6CO0E0FFxhPFoLmeg1C8Gpd_xt8A',
    appId: '1:136199316151:web:e32e5e05e8b6bb6a91e332',
    messagingSenderId: '136199316151',
    projectId: 'asset-management-app-3ec80',
    authDomain: 'asset-management-app-3ec80.firebaseapp.com',
    storageBucket: 'asset-management-app-3ec80.firebasestorage.app',
    measurementId: 'G-VV7RJYVQZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-IpM4zijZ1drHY_-cqXJNtS78gMqvBqo',
    appId: '1:136199316151:android:9d08e4f16353b19491e332',
    messagingSenderId: '136199316151',
    projectId: 'asset-management-app-3ec80',
    storageBucket: 'asset-management-app-3ec80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoiek89PZrcjbyAoy-FZUI4bX9w2a98as',
    appId: '1:136199316151:ios:8c67a99ee3d10b8191e332',
    messagingSenderId: '136199316151',
    projectId: 'asset-management-app-3ec80',
    storageBucket: 'asset-management-app-3ec80.firebasestorage.app',
    iosBundleId: 'com.example.assetManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoiek89PZrcjbyAoy-FZUI4bX9w2a98as',
    appId: '1:136199316151:ios:8c67a99ee3d10b8191e332',
    messagingSenderId: '136199316151',
    projectId: 'asset-management-app-3ec80',
    storageBucket: 'asset-management-app-3ec80.firebasestorage.app',
    iosBundleId: 'com.example.assetManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5vWi6CO0E0FFxhPFoLmeg1C8Gpd_xt8A',
    appId: '1:136199316151:web:4cde323da982d63791e332',
    messagingSenderId: '136199316151',
    projectId: 'asset-management-app-3ec80',
    authDomain: 'asset-management-app-3ec80.firebaseapp.com',
    storageBucket: 'asset-management-app-3ec80.firebasestorage.app',
    measurementId: 'G-E6SKV0L8K6',
  );
}
